name: Deploy app.skyfi.social

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to deploy from social-app repo'
        required: true
        default: 'skyfi'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout social-app repository
      uses: actions/checkout@v4
      with:
        repository: skyfi-social/social-app
        ref: ${{ inputs.branch }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build web application
      run: yarn build-web
    
    - name: Create CNAME file for app.skyfi.social
      run: echo "app.skyfi.social" > ./web-build/CNAME
    
    - name: Copy client-metadata.json to web-build
      run: cp ./app.skyfi.social/client-metadata.json ./web-build/
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./web-build
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-app-skyfi-social"
  cancel-in-progress: false